name: Test Pipeline

on:
  # set up ohw the workflow is triggered
  push:
    branches:
      - main

  schedule:
    - cron: "35 22 * * 1-5"

  # allow riggering  this workflow manually from the actions tab
  workflow_dispatch:

jobs:
  # job # 1, "build-and-test"
  build-and-test:
    # runner environment to use
    runs-on: ubuntu-latest

    # each step begins with a hyphen
    steps:
      # checkes out your repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: echo Entering Test Pipeline

        # this installs python 3.9 to the runner environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run all tests
        run: pytest -v
